services:
  db:
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fakenews
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db

  seeder:
    image: php:8.2-cli
    volumes:
      - ./seeder:/app
    entrypoint: ["php", "/app/seed.php"]
    depends_on:
      - db
